<?php
$turkey_data = array (
  'istanbul' => 
  array (
    'name' => 'İstanbul',
    'ilceler' => 
    array (
      'adalar' => 
      array (
        'name' => 'Adalar',
        'mahalleler' => 
        array (
          'burgazada' => 'Burgazada',
          'heybeliada' => 'Heybeliada',
          'kinaliada' => 'Kınalıada',
          'maden' => 'Maden',
          'nizam' => 'Nizam',
        ),
      ),
      'arnavutkoy' => 
      array (
        'name' => 'Arnavutköy',
        'mahalleler' => 
        array (
          'adnan-menderes' => 'Adnan Menderes',
          'anadolu' => 'Anadolu',
          'arnavutkoy-merkez' => 'Arnavutköy Merkez',
          'ataturk' => 'Atatürk',
          'baklali' => 'Baklalı',
          'balaban' => 'Balaban',
          'bolluca' => 'Bolluca',
          'boyalik' => 'Boyalık',
          'bogazkoy-istiklal' => 'Boğazköy İstiklal',
          'cilingir' => 'Çilingir',
          'deliklikaya' => 'Deliklikaya',
          'dursunkoy' => 'Dursunköy',
          'durusu' => 'Durusu',
          'fatih' => 'Fatih',
          'hacimasli' => 'Hacımaşlı',
          'hadimkoy' => 'Hadımköy',
          'haracci' => 'Haraççı',
          'hastane' => 'Hastane',
          'hicret' => 'Hicret',
          'imrahor' => 'İmrahor',
          'islambey' => 'İslambey',
          'karaburun' => 'Karaburun',
          'karlibayir' => 'Karlıbayır',
          'mavigol' => 'Mavigöl',
          'mehmet-akif-ersoy' => 'Mehmet Akif Ersoy',
          'mustafa-kemal-pasa' => 'Mustafa Kemal Paşa',
          'nenehatun' => 'Nenehatun',
          'omerli' => 'Ömerli',
          'sazlibosna' => 'Sazlıbosna',
          'tasoluk' => 'Taşoluk',
          'tayakadin' => 'Tayakadın',
          'terkos' => 'Terkos',
          'yassioren' => 'Yassıören',
          'yavuz-selim' => 'Yavuz Selim',
          'yenikoy' => 'Yeniköy',
          'yesilbayir' => 'Yeşilbayır',
        ),
      ),
      'atasehir' => 
      array (
        'name' => 'Ataşehir',
        'mahalleler' => 
        array (
          'asik-veysel' => 'Aşık Veysel',
          'ataturk' => 'Atatürk',
          'barbaros' => 'Barbaros',
          'esatpasa' => 'Esatpaşa',
          'ferhatpasa' => 'Ferhatpaşa',
          'fetih' => 'Fetih',
          'icerenkoy' => 'İçerenköy',
          'inonu' => 'İnönü',
          'kayisdagi' => 'Kayışdağı',
          'kucukbakkalkoy' => 'Küçükbakkalköy',
          'mevlana' => 'Mevlana',
          'mimar-sinan' => 'Mimar Sinan',
          'mustafa-kemal' => 'Mustafa Kemal',
          'ornek' => 'Örnek',
          'yeni-camlica' => 'Yeni Çamlıca',
          'yenisahra' => 'Yenisahra',
          'yenisehir' => 'Yenişehir',
        ),
      ),
      'avcilar' => 
      array (
        'name' => 'Avcılar',
        'mahalleler' => 
        array (
          'ambarli' => 'Ambarlı',
          'cihangir' => 'Cihangir',
          'denizkoskler' => 'Denizköşkler',
          'firuzkoy' => 'Firuzköy',
          'gumuspala' => 'Gümüşpala',
          'merkez' => 'Merkez',
          'mustafa-kemal-pasa' => 'Mustafa Kemal Paşa',
          'tahtakale' => 'Tahtakale',
          'universite' => 'Üniversite',
          'yesilkent' => 'Yeşilkent',
        ),
      ),
      'bagcilar' => 
      array (
        'name' => 'Bağcılar',
        'mahalleler' => 
        array (
          '100-yil' => '100. Yıl',
          '15-temmuz' => '15 Temmuz',
          'baglar' => 'Bağlar',
          'barbaros' => 'Barbaros',
          'cinar' => 'Çınar',
          'demirkapi' => 'Demirkapı',
          'fatih' => 'Fatih',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'goztepe' => 'Göztepe',
          'gunesli' => 'Güneşli',
          'hurriyet' => 'Hürriyet',
          'inonu' => 'İnönü',
          'kazim-karabekir' => 'Kazım Karabekir',
          'kemalpasa' => 'Kemalpaşa',
          'kirazli' => 'Kirazlı',
          'mahmutbey' => 'Mahmutbey',
          'merkez' => 'Merkez',
          'sancaktepe' => 'Sancaktepe',
          'yavuz-selim' => 'Yavuz Selim',
          'yenigun' => 'Yenigün',
          'yenimahalle' => 'Yenimahalle',
          'yildiztepe' => 'Yıldıztepe',
        ),
      ),
      'bahcelievler' => 
      array (
        'name' => 'Bahçelievler',
        'mahalleler' => 
        array (
          'bahcelievler' => 'Bahçelievler',
          'cumhuriyet' => 'Cumhuriyet',
          'cobancesme' => 'Çobançeşme',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'hurriyet' => 'Hürriyet',
          'kocasinan-merkez' => 'Kocasinan Merkez',
          'siyavuspasa' => 'Siyavuşpaşa',
          'soganli' => 'Soğanlı',
          'sirinevler' => 'Şirinevler',
          'yenibosna-merkez' => 'Yenibosna Merkez',
          'zafer' => 'Zafer',
        ),
      ),
      'bakirkoy' => 
      array (
        'name' => 'Bakırköy',
        'mahalleler' => 
        array (
          'atakoy-1-kisim' => 'Ataköy 1. Kısım',
          'atakoy-2-5-6-kisim' => 'Ataköy 2-5-6. Kısım',
          'atakoy-3-4-11-kisim' => 'Ataköy 3-4-11. Kısım',
          'atakoy-7-8-9-10-kisim' => 'Ataköy 7-8-9-10. Kısım',
          'basinkoy' => 'Basınköy',
          'cevizlik' => 'Cevizlik',
          'kartaltepe' => 'Kartaltepe',
          'osmaniye' => 'Osmaniye',
          'sakizagaci' => 'Sakızağacı',
          'senlikkoy' => 'Şenlikköy',
          'yenimahalle' => 'Yenimahalle',
          'yesilkoy' => 'Yeşilköy',
          'yesilyurt' => 'Yeşilyurt',
          'zeytinlik' => 'Zeytinlik',
          'zuhuratbaba' => 'Zuhuratbaba',
        ),
      ),
      'basaksehir' => 
      array (
        'name' => 'Başakşehir',
        'mahalleler' => 
        array (
          'altinsehir' => 'Altınşehir',
          'bahcesehir-1-kisim' => 'Bahçeşehir 1. Kısım',
          'bahcesehir-2-kisim' => 'Bahçeşehir 2. Kısım',
          'basak' => 'Başak',
          'basaksehir' => 'Başakşehir',
          'guvercintepe' => 'Güvercintepe',
          'kayabasi' => 'Kayabaşı',
          'sahintepe' => 'Şahintepe',
          'samlar' => 'Şamlar',
          'ziya-gokalp' => 'Ziya Gökalp',
        ),
      ),
      'bayrampasa' => 
      array (
        'name' => 'Bayrampaşa',
        'mahalleler' => 
        array (
          'altintepsi' => 'Altıntepsi',
          'cevatpasa' => 'Cevatpaşa',
          'ismetpasa' => 'İsmetpaşa',
          'kartaltepe' => 'Kartaltepe',
          'kocatepe' => 'Kocatepe',
          'muratpasa' => 'Muratpaşa',
          'orta' => 'Orta',
          'terazidere' => 'Terazidere',
          'vatan' => 'Vatan',
          'yenidogan' => 'Yenidoğan',
          'yildirim' => 'Yıldırım',
        ),
      ),
      'besiktas' => 
      array (
        'name' => 'Beşiktaş',
        'mahalleler' => 
        array (
          'abbasaga' => 'Abbasağa',
          'akat' => 'Akat',
          'arnavutkoy' => 'Arnavutköy',
          'balmumcu' => 'Balmumcu',
          'bebek' => 'Bebek',
          'cihannuma' => 'Cihannüma',
          'dikilitas' => 'Dikilitaş',
          'etiler' => 'Etiler',
          'gayrettepe' => 'Gayrettepe',
          'konaklar' => 'Konaklar',
          'kurucesme' => 'Kuruçeşme',
          'kultur' => 'Kültür',
          'levazim' => 'Levazım',
          'levent' => 'Levent',
          'mecidiye' => 'Mecidiye',
          'muradiye' => 'Muradiye',
          'nisbetiye' => 'Nisbetiye',
          'ortakoy' => 'Ortaköy',
          'sinanpasa' => 'Sinanpaşa',
          'turkali' => 'Türkali',
          'ulus' => 'Ulus',
          'visnezade' => 'Vişnezade',
          'yildiz' => 'Yıldız',
        ),
      ),
      'beykoz' => 
      array (
        'name' => 'Beykoz',
        'mahalleler' => 
        array (
          'acarlar' => 'Acarlar',
          'akbaba' => 'Akbaba',
          'alibahadir' => 'Alibahadır',
          'anadolu-hisari' => 'Anadolu Hisarı',
          'anadolu-kavagi' => 'Anadolu Kavağı',
          'anadolufeneri' => 'Anadolufeneri',
          'baklaci' => 'Baklacı',
          'bozhane' => 'Bozhane',
          'cubuklu' => 'Çubuklu',
          'cumhuriyet' => 'Cumhuriyet',
          'camlibahce' => 'Çamlıbahçe',
          'cengeldere' => 'Çengeldere',
          'cigdem' => 'Çiğdem',
          'ciftlik' => 'Çiftlik',
          'dereagzi' => 'Dereağzı',
          'dereseki' => 'Dereseki',
          'elmali' => 'Elmalı',
          'fatih' => 'Fatih',
          'goksu' => 'Göksu',
          'gollu' => 'Göllü',
          'gorele' => 'Görele',
          'gumussuyu' => 'Gümüşsuyu',
          'incirkoy' => 'İncirköy',
          'ishakli' => 'İshaklı',
          'kanlica' => 'Kanlıca',
          'kavacik' => 'Kavacık',
          'kaynarca' => 'Kaynarca',
          'kilicli' => 'Kılıçlı',
          'mahmutsevketpasa' => 'Mahmutşevketpaşa',
          'merkez' => 'Merkez',
          'ortacesme' => 'Ortaçeşme',
          'ogumce' => 'Öğümce',
          'ornekkoy' => 'Örnekköy',
          'pasabahce' => 'Paşabahçe',
          'pasamandira' => 'Paşamandıra',
          'polonezkoy' => 'Polonezköy',
          'poyrazkoy' => 'Poyrazköy',
          'riva' => 'Riva',
          'ruzgarlibahce' => 'Rüzgarlıbahçe',
          'soguksu' => 'Soğuksu',
          'tokatkoy' => 'Tokatköy',
          'yavuz-selim' => 'Yavuz Selim',
          'yeni-mahalle' => 'Yeni Mahalle',
          'zerzavatci' => 'Zerzavatçı',
        ),
      ),
      'beylikduzu' => 
      array (
        'name' => 'Beylikdüzü',
        'mahalleler' => 
        array (
          'adnan-kahveci' => 'Adnan Kahveci',
          'baris' => 'Barış',
          'buyuksehir' => 'Büyükşehir',
          'cumhuriyet' => 'Cumhuriyet',
          'dereagzi' => 'Dereağzı',
          'gurpinar' => 'Gürpınar',
          'kavakli' => 'Kavaklı',
          'marmara' => 'Marmara',
          'sahil' => 'Sahil',
          'yakuplu' => 'Yakuplu',
        ),
      ),
      'beyoglu' => 
      array (
        'name' => 'Beyoğlu',
        'mahalleler' => 
        array (
          'arapcami' => 'Arapcami',
          'asmalimescit' => 'Asmalımescit',
          'bedrettin' => 'Bedrettin',
          'bereketzade' => 'Bereketzade',
          'bostan' => 'Bostan',
          'bulbul' => 'Bülbül',
          'camiikebir' => 'Camiikebir',
          'cihangir' => 'Cihangir',
          'catmamescit' => 'Çatmamescit',
          'cukur' => 'Çukur',
          'emlakyemez' => 'Emlakyemez',
          'evliya-celebi' => 'Evliya Çelebi',
          'fetihtepe' => 'Fetihtepe',
          'firuzaga' => 'Firuzağa',
          'gumussuyu' => 'Gümüşsuyu',
          'haciahmet' => 'Hacıahmet',
          'hacimimi' => 'Hacımimi',
          'halicioglu' => 'Halıcıoğlu',
          'huseyinaga' => 'Hüseyinağa',
          'istiklal' => 'İstiklal',
          'kadi-mehmet-efendi' => 'Kadı Mehmet Efendi',
          'kamer-hatun' => 'Kamer Hatun',
          'kalyoncu-kullugu' => 'Kalyoncu Kulluğu',
          'kaptanpasa' => 'Kaptanpaşa',
          'katip-mustafa-celebi' => 'Katip Mustafa Çelebi',
          'kececipiri' => 'Keçecipiri',
          'kemankes-kara-mustafa-pasa' => 'Kemankeş Kara Mustafa Paşa',
          'kucuk-piyale' => 'Küçük Piyale',
          'kuloglu' => 'Kuloğlu',
          'kulaksiz' => 'Kulaksız',
          'mueyyedzade' => 'Müeyyedzade',
          'ornektepe' => 'Örnektepe',
          'piripasa' => 'Piripaşa',
          'piyalepasa' => 'Piyalepaşa',
          'purtelas-hasan-efendi' => 'Pürtelaş Hasan Efendi',
          'sururi-mehmet-efendi' => 'Sururi Mehmet Efendi',
          'sutluce' => 'Sütlüce',
          'sahkulu' => 'Şahkulu',
          'sehit-muhtar' => 'Şehit Muhtar',
          'tomtom' => 'Tomtom',
          'yahya-kahya' => 'Yahya Kahya',
          'yenisehir' => 'Yenişehir',
        ),
      ),
      'buyukcekmece' => 
      array (
        'name' => 'Büyükçekmece',
        'mahalleler' => 
        array (
          '19-mayis' => '19 Mayıs',
          'ahmediye' => 'Ahmediye',
          'alkent-2000' => 'Alkent 2000',
          'ataturk' => 'Atatürk',
          'bahcelievler' => 'Bahçelievler',
          'celaliye' => 'Celaliye',
          'cumhuriyet' => 'Cumhuriyet',
          'cakmakli' => 'Çakmaklı',
          'dizdariye' => 'Dizdariye',
          'ekinoba' => 'Ekinoba',
          'fatih' => 'Fatih',
          'guzelce' => 'Güzelce',
          'hurriyet' => 'Hürriyet',
          'kamiloba' => 'Kamiloba',
          'karaagac' => 'Karaağaç',
          'kumburgaz-merkez' => 'Kumburgaz Merkez',
          'mimaroba' => 'Mimaroba',
          'mimarsinan-merkez' => 'Mimarsinan Merkez',
          'muratcesme' => 'Muratçeşme',
          'pinartepe' => 'Pınartepe',
          'sinanoba' => 'Sinanoba',
          'tepecik' => 'Tepecik',
          'turkoba' => 'Türkoba',
          'ulus' => 'Ulus',
        ),
      ),
      'catalca' => 
      array (
        'name' => 'Çatalca',
        'mahalleler' => 
        array (
          'akalan' => 'Akalan',
          'ataturk' => 'Atatürk',
          'aydinlar' => 'Aydınlar',
          'bahsayis' => 'Bahşayiş',
          'basakkoy' => 'Başakköy',
          'belgrat' => 'Belgrat',
          'celepkoy' => 'Celepköy',
          'camlica' => 'Çamlıca',
          'canakca' => 'Çanakça',
          'ciftlikkoy' => 'Çiftlikköy',
          'dagyenice' => 'Dağyenice',
          'elbasan' => 'Elbasan',
          'fatih' => 'Fatih',
          'ferhatpasa' => 'Ferhatpaşa',
          'gokceali' => 'Gökçeali',
          'gumuspinar' => 'Gümüşpınar',
          'halli' => 'Hallı',
          'hisarbeyli' => 'Hisarbeyli',
          'incegiz' => 'İnceğiz',
          'ihsaniye' => 'İhsaniye',
          'kabakca' => 'Kabakça',
          'kalfa' => 'Kalfa',
          'karacakoy-merkez' => 'Karacaköy Merkez',
          'kaleici' => 'Kaleiçi',
          'kestanelik' => 'Kestanelik',
          'kizilcaali' => 'Kızılcaali',
          'muratbey' => 'Muratbey',
          'nakkas' => 'Nakkaş',
          'oklali' => 'Oklalı',
          'ormanli' => 'Ormanlı',
          'ovayenice' => 'Ovayenice',
          'orcunlu' => 'Örcünlü',
          'orencik' => 'Örencik',
          'subasi' => 'Subaşı',
          'yalikoy' => 'Yalıköy',
          'yazlik' => 'Yazlık',
        ),
      ),
      'cekmekoy' => 
      array (
        'name' => 'Çekmeköy',
        'mahalleler' => 
        array (
          'alemdag' => 'Alemdağ',
          'aydinlar' => 'Aydınlar',
          'catalmese' => 'Çatalmeşe',
          'cumhuriyet' => 'Cumhuriyet',
          'camlik' => 'Çamlık',
          'eksioglu' => 'Ekşioğlu',
          'gungoren' => 'Güngören',
          'hamidiye' => 'Hamidiye',
          'huseyinli' => 'Hüseyinli',
          'kirazlidere' => 'Kirazlıdere',
          'kocullu' => 'Koçullu',
          'mehmet-akif' => 'Mehmet Akif',
          'merkez' => 'Merkez',
          'mimar-sinan' => 'Mimar Sinan',
          'nisantepe' => 'Nişantepe',
          'omerli' => 'Ömerli',
          'resadiye' => 'Reşadiye',
          'sirapinar' => 'Sırapınar',
          'sogukpinar' => 'Soğukpınar',
          'sultanciftligi' => 'Sultançiftliği',
          'tasdelen' => 'Taşdelen',
        ),
      ),
      'esenler' => 
      array (
        'name' => 'Esenler',
        'mahalleler' => 
        array (
          'birlik' => 'Birlik',
          'cifte-havuzlar' => 'Çifte Havuzlar',
          'davutpasa' => 'Davutpaşa',
          'fatih' => 'Fatih',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'havaalani' => 'Havaalanı',
          'kazim-karabekir' => 'Kazım Karabekir',
          'kemer' => 'Kemer',
          'menderes' => 'Menderes',
          'mimarsinan' => 'Mimarsinan',
          'namik-kemal' => 'Namık Kemal',
          'nenehatun' => 'Nenehatun',
          'oruc-reis' => 'Oruçreis',
          'tuna' => 'Tuna',
          'turgut-reis' => 'Turgutreis',
          'yavuz-selim' => 'Yavuz Selim',
        ),
      ),
      'esenyurt' => 
      array (
        'name' => 'Esenyurt',
        'mahalleler' => 
        array (
          'akcaburgaz' => 'Akçaburgaz',
          'akevler' => 'Akevler',
          'aksemseddin' => 'Akşemseddin',
          'ardicli' => 'Ardıçlı',
          'asik-veysel' => 'Aşık Veysel',
          'ataturk' => 'Atatürk',
          'baglarcesme' => 'Bağlarçeşme',
          'balikyolu' => 'Balıkyolu',
          'barbaros-hayrettin-pasa' => 'Barbaros Hayrettin Paşa',
          'battalgazi' => 'Battalgazi',
          'cumhuriyet' => 'Cumhuriyet',
          'cinar' => 'Çınar',
          'eski' => 'Esenkent',
          'fatih' => 'Fatih',
          'gokevler' => 'Gökevler',
          'guzelyurt' => 'Güzelyurt',
          'hurriyet' => 'Hürriyet',
          'incirtepe' => 'İncirtepe',
          'inonu' => 'İnönü',
          'istiklal' => 'İstiklal',
          'koza' => 'Koza',
          'mehtercesme' => 'Mehterçeşme',
          'mevlana' => 'Mevlana',
          'namik-kemal' => 'Namık Kemal',
          'necip-fazil-kisakurek' => 'Necip Fazıl Kısakürek',
          'ornek' => 'Örnek',
          'pinar' => 'Pınar',
          'pirireis' => 'Pirireis',
          'saadetdere' => 'Saadetdere',
          'salahaddin-eyyubi' => 'Salahaddin Eyyubi',
          'sultaniye' => 'Sultaniye',
          'suleymaniye' => 'Süleymaniye',
          'sehitler' => 'Şehitler',
          'talatpasa' => 'Talatpaşa',
          'turgut-ozal' => 'Turgut Özal',
          'ucevler' => 'Üçevler',
          'yenikent' => 'Yenikent',
          'yesilkent' => 'Yeşilkent',
          'yunus-emre' => 'Yunus Emre',
          'zafer' => 'Zafer',
        ),
      ),
      'eyupsultan' => 
      array (
        'name' => 'Eyüpsultan',
        'mahalleler' => 
        array (
          '5-levent' => '5. Levent',
          'agacli' => 'Ağaçlı',
          'akpinar' => 'Akpınar',
          'aksemseddin' => 'Akşemsettin',
          'alibeykoy' => 'Alibeyköy',
          'circir' => 'Çırçır',
          'ciftalan' => 'Çiftalan',
          'defterdar' => 'Defterdar',
          'dugmeciler' => 'Düğmeciler',
          'emniyettepe' => 'Emniyettepe',
          'esentepe' => 'Esentepe',
          'eyup-merkez' => 'Eyüp Merkez',
          'gokturk-merkez' => 'Göktürk Merkez',
          'guzeltepe' => 'Güzeltepe',
          'isiklar' => 'Işıklar',
          'ihsaniye' => 'İhsaniye',
          'islam-bey' => 'İslambey',
          'karadolap' => 'Karadolap',
          'kemerburgaz-merkez' => 'Kemerburgaz Merkez',
          'mimarsinan' => 'Mimarsinan',
          'mithatpasa' => 'Mithatpaşa',
          'nisanci' => 'Nişancı',
          'odayeri' => 'Odayeri',
          'pirincci' => 'Pirinççi',
          'ramicuma' => 'Ramicuma',
          'ramiyeni' => 'Ramiyeni',
          'sakarya' => 'Sakarya',
          'sancaktepe' => 'Sancaktepe',
          'silahtaraga' => 'Silahtarağa',
          'topcular' => 'Topçular',
          'yesilpinar' => 'Yeşilpınar',
        ),
      ),
      'fatih' => 
      array (
        'name' => 'Fatih',
        'mahalleler' => 
        array (
          'aksemseddin' => 'Akşemsettin',
          'alemdar' => 'Alemdar',
          'ali-kuscu' => 'Ali Kuşçu',
          'atikalipasa' => 'Atikali',
          'ayvansaray' => 'Ayvansaray',
          'balabanaga' => 'Balabanağa',
          'balat' => 'Balat',
          'beyazit' => 'Beyazıt',
          'binbirdirek' => 'Binbirdirek',
          'can-kurtaran' => 'Cankurtaran',
          'cerrahpasa' => 'Cerrahpaşa',
          'cibali' => 'Cibali',
          'demirtas' => 'Demirtaş',
          'dervis-ali' => 'Derviş Ali',
          'emin-sinan' => 'Emin Sinan',
          'hacikadin' => 'Hacıkadın',
          'haseki-sultan' => 'Haseki Sultan',
          'hirka-i-serif' => 'Hırka-i Şerif',
          'hobyar' => 'Hobyar',
          'hoca-giyasettin' => 'Hoca Gıyasettin',
          'hocapasa' => 'Hocapaşa',
          'iskenderpasa' => 'İskenderpaşa',
          'kalenderhane' => 'Kalenderhane',
          'karagumruk' => 'Karagümrük',
          'katip-kasim' => 'Katip Kasım',
          'kemalpasa' => 'Kemalpaşa',
          'kucuk-ayasofya' => 'Küçük Ayasofya',
          'kocamustafapasa' => 'Kocamustafapaşa',
          'mercan' => 'Mercan',
          'mesihpasa' => 'Mesihpaşa',
          'mevlanakapi' => 'Mevlanakapı',
          'mimar-hayrettin' => 'Mimar Hayrettin',
          'mimar-kemalettin' => 'Mimar Kemalettin',
          'molla-fenari' => 'Molla Fenari',
          'molla-gurani' => 'Molla Gürani',
          'molla-husrev' => 'Molla Hüsrev',
          'muhsine-hatun' => 'Muhsine Hatun',
          'nisanca' => 'Nişanca',
          'rustempasa' => 'Rüstempaşa',
          'sarac-ishak' => 'Saraç İshak',
          'saridemir' => 'Sarıdemir',
          'seyyid-omer' => 'Seyyid Ömer',
          'silivrikapi' => 'Silivrikapı',
          'sultanahmet' => 'Sultanahmet',
          'sururi' => 'Sururi',
          'suleymaniye' => 'Süleymaniye',
          'sunbul-efendi' => 'Sünbül Efendi',
          'sehremini' => 'Şehremini',
          'sehsuvar-bey' => 'Şehsuvar Bey',
          'tahtakale' => 'Tahtakale',
          'taya-hatun' => 'Taya Hatun',
          'topkapi' => 'Topkapı',
          'yavuz-selim' => 'Yavuz Selim',
          'yavuz-sinan' => 'Yavuz Sinan',
          'yedikule' => 'Yedikule',
          'zeyrek' => 'Zeyrek',
        ),
      ),
      'gaziosmanpasa' => 
      array (
        'name' => 'Gaziosmanpaşa',
        'mahalleler' => 
        array (
          'baglarbasi' => 'Bağlarbaşı',
          'barbaros-hayrettin-pasa' => 'Barbaros Hayrettin Paşa',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'hurriyet' => 'Hürriyet',
          'karadeniz' => 'Karadeniz',
          'karayollari' => 'Karayolları',
          'karlitepe' => 'Karlıtepe',
          'kazim-karabekir' => 'Kazım Karabekir',
          'merkez' => 'Merkez',
          'mevlana' => 'Mevlana',
          'pazarici' => 'Pazariçi',
          'sarigol' => 'Sarıgöl',
          'semsipasa' => 'Şemsipaşa',
          'yeni-mahalle' => 'Yeni Mahalle',
          'yenidogan' => 'Yenidoğan',
          'yildiztabya' => 'Yıldıztabya',
        ),
      ),
      'gungoren' => 
      array (
        'name' => 'Güngören',
        'mahalleler' => 
        array (
          'abdurrahman-nafiz-gurman' => 'Abdürrahman Nafiz Gürman',
          'akincilar' => 'Akıncılar',
          'gencosman' => 'Gençosman',
          'gunestepe' => 'Güneştepe',
          'guven' => 'Güven',
          'haznedar' => 'Haznedar',
          'maresal-cakmak' => 'Mareşal Çakmak',
          'mehmet-nesih-ozmen' => 'Mehmet Nesih Özmen',
          'merkez' => 'Merkez',
          'sanayi' => 'Sanayi',
          'tozkoparan' => 'Tozkoparan',
        ),
      ),
      'kadikoy' => 
      array (
        'name' => 'Kadıköy',
        'mahalleler' => 
        array (
          '19-mayis' => '19 Mayıs',
          'acibadem' => 'Acıbadem',
          'bostanci' => 'Bostancı',
          'caddebostan' => 'Caddebostan',
          'caferaga' => 'Caferağa',
          'dumlupinar' => 'Dumlupınar',
          'egitim' => 'Eğitim',
          'erenkoy' => 'Erenköy',
          'fenerbahce' => 'Fenerbahçe',
          'feneryolu' => 'Feneryolu',
          'fikirtepe' => 'Fikirtepe',
          'goztepe' => 'Göztepe',
          'hasanpasa' => 'Hasanpaşa',
          'kosuyolu' => 'Koşuyolu',
          'kozyatagi' => 'Kozyatağı',
          'merdivenkoy' => 'Merdivenköy',
          'osmanaga' => 'Osmanağa',
          'rasimpasa' => 'Rasimpaşa',
          'sahrayicedit' => 'Sahrayıcedit',
          'suadiye' => 'Suadiye',
          'zuhtupasa' => 'Zühtüpaşa',
        ),
      ),
      'kagithane' => 
      array (
        'name' => 'Kağıthane',
        'mahalleler' => 
        array (
          'caglayan' => 'Çağlayan',
          'celiktepe' => 'Çeliktepe',
          'emniyetevleri' => 'Emniyetevleri',
          'gultepe' => 'Gültepe',
          'gursel' => 'Gürsel',
          'hamidiye' => 'Hamidiye',
          'harmantepe' => 'Harmantepe',
          'hurriyet' => 'Hürriyet',
          'mehmet-akif-ersoy' => 'Mehmet Akif Ersoy',
          'merkez' => 'Merkez',
          'nurtepe' => 'Nurtepe',
          'ortabayir' => 'Ortabayır',
          'sanayi' => 'Sanayi',
          'seyratepe' => 'Seyrantepe',
          'sirintepe' => 'Şirintepe',
          'telsizler' => 'Telsizler',
          'yahya-kemal' => 'Yahya Kemal',
          'yenisehir' => 'Yenişehir',
          'yesilce' => 'Yeşilce',
        ),
      ),
      'kartal' => 
      array (
        'name' => 'Kartal',
        'mahalleler' => 
        array (
          'atilar' => 'Atalar',
          'cavusoglu' => 'Çavuşoğlu',
          'cumhuriyet' => 'Cumhuriyet',
          'esentepe' => 'Esentepe',
          'gumuspinar' => 'Gümüşpınar',
          'hurriyet' => 'Hürriyet',
          'karliktepe' => 'Karlıktepe',
          'kordonboyu' => 'Kordonboyu',
          'orhan-tepe' => 'Orhantepe',
          'orta' => 'Orta',
          'petrolis' => 'Petroliş',
          'soganlik-yeni' => 'Soğanlık Yeni',
          'topselvi' => 'Topselvi',
          'ugur-mumcu' => 'Uğur Mumcu',
          'yakacik-carsi' => 'Yakacık Çarşı',
          'yakacik-yeni' => 'Yakacık Yeni',
          'yali' => 'Yalı',
          'yukari' => 'Yukarı',
        ),
      ),
      'kucukcekmece' => 
      array (
        'name' => 'Küçükçekmece',
        'mahalleler' => 
        array (
          'atakent' => 'Atakent',
          'ataturk' => 'Atatürk',
          'besyol' => 'Beşyol',
          'cennet' => 'Cennet',
          'cumhuriyet' => 'Cumhuriyet',
          'fatih' => 'Fatih',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'gultepe' => 'Gültepe',
          'halkali-merkez' => 'Halkalı Merkez',
          'inonu' => 'İnönü',
          'istasyon' => 'İstasyon',
          'kanarya' => 'Kanarya',
          'kartaltepe' => 'Kartaltepe',
          'kemalpasa' => 'Kemalpaşa',
          'mehmet-akif' => 'Mehmet Akif',
          'sogutlu-cesme' => 'Söğütlü Çeşme',
          'sultan-murat' => 'Sultan Murat',
          'tevfikbey' => 'Tevfikbey',
          'yarimburgaz' => 'Yarımburgaz',
          'yenimahalle' => 'Yenimahalle',
          'yesilova' => 'Yeşilova',
        ),
      ),
      'maltepe' => 
      array (
        'name' => 'Maltepe',
        'mahalleler' => 
        array (
          'adatepe' => 'Adatepe',
          'altaycesme' => 'Altayçeşme',
          'altintepe' => 'Altıntepe',
          'aydinevler' => 'Aydınevler',
          'baglarbasi' => 'Bağlarbaşı',
          'basibuyuk' => 'Başıbüyük',
          'buyukbakkalkoy' => 'Büyükbakkalköy',
          'cevizli' => 'Cevizli',
          'cinar' => 'Çınar',
          'esenkent' => 'Esenkent',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'findikli' => 'Fındıklı',
          'girne' => 'Girne',
          'gulensu' => 'Gülensu',
          'gulsuyu' => 'Gülsuyu',
          'idealtepe' => 'İdealtepe',
          'kucukyali-merkez' => 'Küçükyalı Merkez',
          'yali' => 'Yalı',
          'zumrutevler' => 'Zümrütevler',
        ),
      ),
      'pendik' => 
      array (
        'name' => 'Pendik',
        'mahalleler' => 
        array (
          'ahmet-yesevi' => 'Ahmet Yesevi',
          'bahcelievler' => 'Bahçelievler',
          'ballica' => 'Ballıca',
          'bati' => 'Batı',
          'cinardere' => 'Çınardere',
          'dogu' => 'Doğu',
          'dumlupinar' => 'Dumlupınar',
          'ertugrul-gazi' => 'Ertuğrul Gazi',
          'esenyali' => 'Esenyalı',
          'fatih' => 'Fatih',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'gocbeyli' => 'Göçbeyli',
          'gullu-baglar' => 'Güllü Bağlar',
          'guzel-yali' => 'Güzelyalı',
          'harmandere' => 'Harmandere',
          'kavakpinar' => 'Kavakpınar',
          'kaynarca' => 'Kaynarca',
          'kurna' => 'Kurna',
          'kurtdogmus' => 'Kurtdoğmuş',
          'kurtkoy' => 'Kurtköy',
          'orhan-gazi' => 'Orhan Gazi',
          'orta' => 'Orta',
          'ramazanoglu' => 'Ramazanoğlu',
          'sanayi' => 'Sanayi',
          'sapan-baglari' => 'Sapan Bağları',
          'seyli' => 'Şeyhli',
          'suluntepe' => 'Sülüntepe',
          'velibaba' => 'Velibaba',
          'yayalar' => 'Yayalar',
          'yeni' => 'Yeni',
          'yenisehir' => 'Yenişehir',
          'yesilbaglar' => 'Yeşilbağlar',
        ),
      ),
      'sancaktepe' => 
      array (
        'name' => 'Sancaktepe',
        'mahalleler' => 
        array (
          'abdurrahmangazi' => 'Abdurrahmangazi',
          'akpinar' => 'Akpınar',
          'ataturk' => 'Atatürk',
          'emek' => 'Emek',
          'eyup-sultan' => 'Eyüp Sultan',
          'fatih' => 'Fatih',
          'hilal' => 'Hilal',
          'inonu' => 'İnönü',
          'kemal-turkler' => 'Kemal Türkler',
          'meclis' => 'Meclis',
          'merve' => 'Merve',
          'mevlana' => 'Mevlana',
          'osman-gazi' => 'Osman Gazi',
          'pasakoy' => 'Paşaköy',
          'safa' => 'Safa',
          'sarigazi' => 'Sarıgazi',
          'veysel-karani' => 'Veysel Karani',
          'yeni-dogan' => 'Yeni Doğan',
          'yunus-emre' => 'Yunus Emre',
        ),
      ),
      'sariyer' => 
      array (
        'name' => 'Sarıyer',
        'mahalleler' => 
        array (
          'baltalimani' => 'Baltalimanı',
          'buyukdere' => 'Büyükdere',
          'cumhuriyet' => 'Cumhuriyet',
          'cayirbasi' => 'Çayırbaşı',
          'darussafaka' => 'Darüşşafaka',
          'demircikoy' => 'Demirciköy',
          'emirgan' => 'Emirgan',
          'fatih-sultan-mehmet' => 'Fatih Sultan Mehmet',
          'ferahevler' => 'Ferahevler',
          'garipce' => 'Garipçe',
          'gumusdere' => 'Gümüşdere',
          'huzur' => 'Huzur',
          'istinye' => 'İstinye',
          'kazim-karabekir-pasa' => 'Kazım Karabekir Paşa',
          'kemer' => 'Kemer',
          'kirecburnu' => 'Kireçburnu',
          'kisirkaya' => 'Kısırkaya',
          'kocatas' => 'Kocataş',
          'kumkoy' => 'Kumköy',
          'maden' => 'Maden',
          'maslak' => 'Maslak',
          'merkez' => 'Merkez',
          'pinar' => 'Pınar',
          'poligon' => 'Poligon',
          'ptt-evleri' => 'PTT Evleri',
          'resitpasa' => 'Reşitpaşa',
          'rumeli-feneri' => 'Rumeli Feneri',
          'rumeli-hisari' => 'Rumeli Hisarı',
          'rumeli-kavagi' => 'Rumeli Kavağı',
          'tarabya' => 'Tarabya',
          'uskumrukoy' => 'Uskumruköy',
          'yeni' => 'Yeni',
          'yenikoy' => 'Yeniköy',
        ),
      ),
      'silivri' => 
      array (
        'name' => 'Silivri',
        'mahalleler' => 
        array (
          'akkoren' => 'Akkören',
          'alibey' => 'Alibey',
          'alipasa' => 'Alipaşa',
          'balaban' => 'Balaban',
          'bekirli' => 'Bekirli',
          'beyciler' => 'Beyciler',
          'buyuk-cavuslu' => 'Büyük Çavuşlu',
          'buyuk-kilicli' => 'Büyük Kılıçlı',
          'cumhuriyet' => 'Cumhuriyet',
          'cayirdere' => 'Çayırdere',
          'celtik' => 'Çeltik',
          'danamandira' => 'Danamandıra',
          'fatih' => 'Fatih',
          'fenerkoy' => 'Fenerköy',
          'gazitepe' => 'Gazitepe',
          'gumusyaka' => 'Gümüşyaka',
          'hurriyet' => 'Hürriyet',
          'ismetpasa' => 'İsmetpaşa',
          'kadikoy' => 'Kadıköy',
          'kavakli' => 'Kavaklı',
          'kucuk-kilicli' => 'Küçük Kılıçlı',
          'kucuksinekli' => 'Küçüksinekli',
          'kurfalli' => 'Kurfallı',
          'mimarsinan' => 'Mimarsinan',
          'ortakoy' => 'Ortaköy',
          'piri-mehmet-pasa' => 'Piri Mehmet Paşa',
          'sayalar' => 'Sayalar',
          'selimpasa' => 'Selimpaşa',
          'seymen' => 'Seymen',
          'sinekli' => 'Sinekli',
          'yeni' => 'Yeni',
        ),
      ),
      'sultanbeyli' => 
      array (
        'name' => 'Sultanbeyli',
        'mahalleler' => 
        array (
          'abdurrahmangazi' => 'Abdurrahmangazi',
          'adil' => 'Adil',
          'ahmet-yesevi' => 'Ahmet Yesevi',
          'aksemseddin' => 'Akşemsettin',
          'battal-gazi' => 'Battal Gazi',
          'fatih' => 'Fatih',
          'hamidiye' => 'Hamidiye',
          'hasanpasa' => 'Hasanpaşa',
          'mecidiye' => 'Mecidiye',
          'mehmet-akif' => 'Mehmet Akif',
          'mimar-sinan' => 'Mimar Sinan',
          'necip-fazil' => 'Necip Fazıl',
          'orhan-gazi' => 'Orhan Gazi',
          'turgut-reis' => 'Turgut Reis',
          'yavuz-selim' => 'Yavuz Selim',
        ),
      ),
      'sultangazi' => 
      array (
        'name' => 'Sultangazi',
        'mahalleler' => 
        array (
          '50-yil' => '50. Yıl',
          '75-yil' => '75. Yıl',
          'cebeci' => 'Cebeci',
          'cumhuriyet' => 'Cumhuriyet',
          'esentepe' => 'Esentepe',
          'gazi' => 'Gazi',
          'habibler' => 'Habibler',
          'ismetpasa' => 'İsmetpaşa',
          'kazim-karabekir' => 'Kazım Karabekir',
          'malkocoglu' => 'Malkoçoğlu',
          'sultanciftligi' => 'Sultançiftliği',
          'ugur-mumcu' => 'Uğur Mumcu',
          'yayla' => 'Yayla',
          'yunus-emre' => 'Yunus Emre',
          'zubeyde-hanim' => 'Zübeyde Hanım',
        ),
      ),
      'sile' => 
      array (
        'name' => 'Şile',
        'mahalleler' => 
        array (
          'agacdere' => 'Ağaçdere',
          'agva-merkez' => 'Ağva Merkez',
          'ahmetli' => 'Ahmetli',
          'akcakese' => 'Akçakese',
          'alacali' => 'Alacalı',
          'avcikoru' => 'Avcıkoru',
          'balibey' => 'Balibey',
          'bickidere' => 'Bıçkıdere',
          'bozgoca' => 'Bozgoca',
          'bucakli' => 'Bucaklı',
          'catakli' => 'Çataklı',
          'cavus' => 'Çavuş',
          'celebi' => 'Çelebi',
          'cengilli' => 'Çengilli',
          'darlik' => 'Darlık',
          'degirmencayiri' => 'Değirmençayırı',
          'dogancili' => 'Doğancılı',
          'erenler' => 'Erenler',
          'esenceli' => 'Esenceli',
          'gokmasli' => 'Gökmaslı',
          'goksu' => 'Göksu',
          'hacilli' => 'Hacıllı',
          'hasanli' => 'Hasanlı',
          'imbrenli' => 'İmbrenli',
          'imrahorlu' => 'İmrahorlu',
          'isabeyli' => 'İsabeyli',
          'isakli' => 'İsaköy',
          'kabakoz' => 'Kabakoz',
          'kadikoy' => 'Kadıköy',
          'kalem' => 'Kalem',
          'karabeyli' => 'Karabeyli',
          'karacakoy' => 'Karacaköy',
          'karakiraz' => 'Karakiraz',
          'karamandere' => 'Karamandere',
          'kervansaray' => 'Kervansaray',
          'kizilca' => 'Kızılca',
          'korucu' => 'Korucu',
          'kumbaba' => 'Kumbaba',
          'kurfalli' => 'Kurfallı',
          'kurna' => 'Kurna',
          'mesrutiyet' => 'Meşrutiyet',
          'osmankoy' => 'Osmanköy',
          'ovacik' => 'Ovacık',
          'pasakoy' => 'Paşaköy',
          'satmazli' => 'Satmazlı',
          'sofulu' => 'Sofulu',
          'sortullu' => 'Sortullu',
          'teke' => 'Teke',
          'ulupelit' => 'Ulupelit',
          'uvezli' => 'Üvezli',
          'yaka' => 'Yaka',
          'yazimanayir' => 'Yazımanayır',
          'yenikoy' => 'Yeniköy',
          'yesilvadi' => 'Yeşilvadi',
        ),
      ),
      'sisli' => 
      array (
        'name' => 'Şişli',
        'mahalleler' => 
        array (
          '19-mayis' => '19 Mayıs',
          'bozkurt' => 'Bozkurt',
          'cumhuriyet' => 'Cumhuriyet',
          'duatepe' => 'Duatepe',
          'ergenekon' => 'Ergenekon',
          'esentepe' => 'Esentepe',
          'eskisehir' => 'Eskişehir',
          'ferikoy' => 'Feriköy',
          'fulya' => 'Fulya',
          'gulbahar' => 'Gülbahar',
          'halaskargazi' => 'Halaskargazi',
          'halide-edip-adivar' => 'Halide Edip Adıvar',
          'halil-rifat-pasa' => 'Halil Rıfat Paşa',
          'harbiye' => 'Harbiye',
          'inonu' => 'İnönü',
          'izzetpasa' => 'İzzetpaşa',
          'kaptanpasa' => 'Kaptanpaşa',
          'kustepe' => 'Kuştepe',
          'mahmut-sevket-pasa' => 'Mahmut Şevket Paşa',
          'mecidiyekoy' => 'Mecidiyeköy',
          'mesrutiyet' => 'Meşrutiyet',
          'pasa' => 'Paşa',
          'tesvikiye' => 'Teşvikiye',
          'yayla' => 'Yayla',
        ),
      ),
      'tuzla' => 
      array (
        'name' => 'Tuzla',
        'mahalleler' => 
        array (
          'akfirat' => 'Akfırat',
          'anadolu' => 'Anadolu',
          'aydinli' => 'Aydınlı',
          'aydintepe' => 'Aydıntepe',
          'cami' => 'Cami',
          'evliya-celebi' => 'Evliya Çelebi',
          'fatih' => 'Fatih',
          'icmeler' => 'İçmeler',
          'istasyon' => 'İstasyon',
          'mescit' => 'Mescit',
          'mimarsinan' => 'Mimarsinan',
          'orhanli' => 'Orhanlı',
          'orta' => 'Orta',
          'postane' => 'Postane',
          'sifa' => 'Şifa',
          'tepeoren' => 'Tepeören',
          'yayla' => 'Yayla',
        ),
      ),
      'umraniye' => 
      array (
        'name' => 'Ümraniye',
        'mahalleler' => 
        array (
          'ademyavuz' => 'Adem Yavuz',
          'altinsehir' => 'Altınşehir',
          'asagidudullu' => 'Aşağıdudullu',
          'ataturk' => 'Atatürk',
          'atakent' => 'Atakent',
          'armaganevler' => 'Armağanevler',
          'cemil-meric' => 'Cemil Meriç',
          'cakmak' => 'Çakmak',
          'camlik' => 'Çamlık',
          'dudullu-osb' => 'Dudullu OSB',
          'dumlupinar' => 'Dumlupınar',
          'elmalikent' => 'Elmalıkent',
          'esenevler' => 'Esenevler',
          'esenkent' => 'Esenkent',
          'esensehir' => 'Esenşehir',
          'fatih-sultan-mehmet' => 'Fatih Sultan Mehmet',
          'hekimasi' => 'Hekimbaşı',
          'huzur' => 'Huzur',
          'ihlamurkuyu' => 'Ihlamurkuyu',
          'inkilap' => 'İnkılap',
          'istiklal' => 'İstiklal',
          'kazim-karabekir' => 'Kazım Karabekir',
          'madenler' => 'Madenler',
          'mehmet-akif' => 'Mehmet Akif',
          'namik-kemal' => 'Namık Kemal',
          'necip-fazil' => 'Necip Fazıl',
          'parseller' => 'Parseller',
          'saray' => 'Saray',
          'site' => 'Site',
          'serifali' => 'Şerifali',
          'tantavi' => 'Tantavi',
          'tatlisu' => 'Tatlısu',
          'tepeustu' => 'Tepeüstü',
          'topagaci' => 'Topağacı',
          'yamanevler' => 'Yamanevler',
          'yukaridudullu' => 'Yukarıdudullu',
        ),
      ),
      'uskudar' => 
      array (
        'name' => 'Üsküdar',
        'mahalleler' => 
        array (
          'acibadem' => 'Acıbadem',
          'ahmediye' => 'Ahmediye',
          'altunizade' => 'Altunizade',
          'aziz-mahmut-hudayi' => 'Aziz Mahmut Hüdayi',
          'bahcelievler' => 'Bahçelievler',
          'barbaros' => 'Barbaros',
          'beylerbeyi' => 'Beylerbeyi',
          'bulgurlu' => 'Bulgurlu',
          'burhaniye' => 'Burhaniye',
          'cumhuriyet' => 'Cumhuriyet',
          'cengelkoy' => 'Çengelköy',
          'ferah' => 'Ferah',
          'guzeltepe' => 'Güzeltepe',
          'icadiye' => 'İcadiye',
          'kandilli' => 'Kandilli',
          'kirazlitepe' => 'Kirazlıtepe',
          'kisikli' => 'Kısıklı',
          'kuzguncuk' => 'Kuzguncuk',
          'kucuk-camlica' => 'Küçük Çamlıca',
          'kucuksu' => 'Küçüksu',
          'kupluce' => 'Küplüce',
          'mehmet-akif-ersoy' => 'Mehmet Akif Ersoy',
          'mimar-sinan' => 'Mimar Sinan',
          'murat-reis' => 'Murat Reis',
          'salacak' => 'Salacak',
          'selamiali' => 'Selamiali',
          'selimiye' => 'Selimiye',
          'sultan-tepe' => 'Sultan Tepe',
          'unalan' => 'Ünalan',
          'valide-i-atik' => 'Valide-i Atik',
          'yavuzturk' => 'Yavuztürk',
          'zeynep-kamil' => 'Zeynep Kamil',
        ),
      ),
      'zeytinburnu' => 
      array (
        'name' => 'Zeytinburnu',
        'mahalleler' => 
        array (
          'bes-telsiz' => 'Beştelsiz',
          'cirpici' => 'Çırpıcı',
          'gokalp' => 'Gökalp',
          'kazlicesme' => 'Kazlıçeşme',
          'maltepe' => 'Maltepe',
          'merkezefendi' => 'Merkezefendi',
          'nuripasa' => 'Nuripaşa',
          'seyitnizam' => 'Seyitnizam',
          'sumer' => 'Sümer',
          'telsiz' => 'Telsiz',
          'veliefendi' => 'Veliefendi',
          'yenidogan' => 'Yenidoğan',
          'yesiltepe' => 'Yeşiltepe',
        ),
      ),
    ),
  ),
  'yalova' => 
  array (
    'name' => 'Yalova',
    'ilceler' => 
    array (
      'merkez' => 
      array (
        'name' => 'Merkez',
        'mahalleler' => 
        array (
          'adnan-menderes' => 'Adnan Menderes',
          'bahcelievler' => 'Bahçelievler',
          'baglarbasi' => 'Bağlarbaşı',
          'bayraktepe' => 'Bayraktepe',
          'dere' => 'Dere',
          'fevzi-cakmak' => 'Fevzi Çakmak',
          'gazi-abdurrahman-pasa' => 'Gazi Abdurrahman Paşa',
          'gaziosmanpasa' => 'Gaziosmanpaşa',
          'ismetpasa' => 'İsmetpaşa',
          'kazim-karabekir' => 'Kazım Karabekir',
          'mustafa-kemal-pasa' => 'Mustafa Kemal Paşa',
          'pasakent' => 'Paşakent',
          'rustempasa' => 'Rüstempaşa',
          'suleymanbey' => 'Süleymanbey',
        ),
      ),
      'altinova' => 
      array (
        'name' => 'Altınova',
        'mahalleler' => 
        array (
          'hersek' => 'Hersek',
          'hurriyet' => 'Hürriyet',
          'merkez' => 'Merkez',
        ),
      ),
      'armutlu' => 
      array (
        'name' => 'Armutlu',
        'mahalleler' => 
        array (
          '50-yil' => '50. Yıl',
          'bayir' => 'Bayır',
          'karsiyaka' => 'Karşıyaka',
        ),
      ),
      'cinarcik' => 
      array (
        'name' => 'Çınarcık',
        'mahalleler' => 
        array (
          'calica' => 'Çalıca',
          'harmanlar' => 'Harmanlar',
          'hasanbaba' => 'Hasanbaba',
          'karpuzdere' => 'Karpuzdere',
        ),
      ),
      'ciftlikkoy' => 
      array (
        'name' => 'Çiftlikköy',
        'mahalleler' => 
        array (
          '500-evler' => '500 Evler',
          'ciftlik' => 'Çiftlik',
          'mehmet-akif-ersoy' => 'Mehmet Akif Ersoy',
          'sahil' => 'Sahil',
          'siteler' => 'Siteler',
          'sultaniye' => 'Sultaniye',
        ),
      ),
      'termal' => 
      array (
        'name' => 'Termal',
        'mahalleler' => 
        array (
          'akkoy' => 'Akköy',
          'gokcedere' => 'Gökçedere',
          'uvezpinar' => 'Üvezpınar',
          'yenimahalle' => 'Yenimahalle',
        ),
      ),
    ),
  ),
  'kocaeli' => 
  array (
    'name' => 'Kocaeli',
    'ilceler' => 
    array (
      'izmit' => 
      array (
        'name' => 'İzmit',
        'mahalleler' => 
        array (
          '28-haziran' => '28 Haziran',
          'akarca' => 'Akarca',
          'akcakoca' => 'Akçakoca',
          'akmese-ataturk' => 'Akmeşe Atatürk',
          'akmese-cumhuriyet' => 'Akmeşe Cumhuriyet',
          'alikahya-ataturk' => 'Alikahya Atatürk',
          'alikahya-cumhuriyet' => 'Alikahya Cumhuriyet',
          'alikahya-fatih' => 'Alikahya Fatih',
          'alikahya-merkez' => 'Alikahya Merkez',
          'ambarci' => 'Ambarcı',
          'arizli' => 'Arızlı',
          'arpalikihsaniye' => 'Arpalıkihsaniye',
          'ayazma' => 'Ayazma',
          'bekirdere' => 'Bekirdere',
          'biberoglu' => 'Biberoğlu',
          'bogurgen' => 'Böğürgen',
          'bulduk' => 'Bulduk',
          'cedit' => 'Cedit',
          'cumhuriyet' => 'Cumhuriyet',
          'cayirkoy' => 'Çayırköy',
          'dagkoy' => 'Dağköy',
          'dogan' => 'Doğan',
          'durhasan' => 'Durhasan',
          'dugmeciler' => 'Düğmeciler',
          'emirhan' => 'Emirhan',
          'erenler' => 'Erenler',
          'eseler' => 'Eseler',
          'fatih' => 'Fatih',
          'fethiye' => 'Fethiye',
          'gedikli' => 'Gedikli',
          'gokceoren' => 'Gökçeören',
          'gulbahce-kadriye' => 'Gülbahçe Kadriye',
          'gultepe' => 'Gültepe',
          'gundogdu' => 'Gündoğdu',
          'guvercinlik' => 'Güvercinlik',
          'hacihasan' => 'Hacıhasan',
          'hacihizir' => 'Hacıhızır',
          'hakaniye' => 'Hakaniye',
          'hasanciklar' => 'Hasancıklar',
          'hatipkoy' => 'Hatipköy',
          'kabaoglu' => 'Kabaoğlu',
          'kadikoy' => 'Kadıköy',
          'karaabdulbaki' => 'Karaabdülbaki',
          'karabas' => 'Karabaş',
          'karadenizliler' => 'Karadenizliler',
          'kaynarca' => 'Kaynarca',
          'kisalar' => 'Kısalar',
          'kocatepe' => 'Kocatepe',
          'kozluca' => 'Kozluca',
          'kozluk' => 'Kozluk',
          'korfez' => 'Körfez',
          'kulfalli' => 'Kulfallı',
          'kulmahmut' => 'Kulmahmut',
          'kurtdere' => 'Kurtdere',
          'kurucesme-fatih' => 'Kuruçeşme Fatih',
          'mehmet-ali-pasa' => 'Mehmet Ali Paşa',
          'malta' => 'Malta',
          'mecidiye' => 'Mecidiye',
          'nebihoca' => 'Nebihoca',
          'orhaniye' => 'Orhaniye',
          'orhan' => 'Orhan',
          'omeraga' => 'Ömerağa',
          'sanayi' => 'Sanayi',
          'sapakpinar' => 'Sapakpınar',
          'sariseyh' => 'Sarışeyh',
          'sekbanli' => 'Sekbanlı',
          'sepetci' => 'Sepetçi',
          'serdar' => 'Serdar',
          'suleymaniye' => 'Süleymaniye',
          'suverler' => 'Süverler',
          'sahinler' => 'Şahinler',
          'sirintepe' => 'Şirintepe',
          'tavsantepe' => 'Tavşantepe',
          'tepecik' => 'Tepecik',
          'tepekoy' => 'Tepeköy',
          'terzibayiri' => 'Terzibayırı',
          'topcular' => 'Topçular',
          'turgut' => 'Turgut',
          'tuysuzler' => 'Tüysüzler',
          'veliahmet' => 'Veliahmet',
          'yahyakaptan' => 'Yahyakaptan',
          'yassibag' => 'Yassıbağ',
          'yeni' => 'Yeni',
          'yenice' => 'Yenice',
          'yenidogan' => 'Yenidoğan',
          'yesilova' => 'Yeşilova',
          'zabitan' => 'Zabıtan',
          'zeytinburnu' => 'Zeytinburnu',
        ),
      ),
      'basiskele' => 
      array (
        'name' => 'Başiskele',
        'mahalleler' => 
        array (
          'altinkent' => 'Altınkent',
          'atakent' => 'Atakent',
          'aydinkent' => 'Aydınkent',
          'barbaros' => 'Barbaros',
          'camiduzu' => 'Camidüzü',
          'damlar' => 'Damlar',
          'dogantepe' => 'Doğantepe',
          'dongel' => 'Döngel',
          'fatih' => 'Fatih',
          'havuzlubahce' => 'Havuzlubahçe',
          'karadenizliler' => 'Karadenizliler',
          'karsiyaka' => 'Karşıyaka',
          'kazandere' => 'Kazandere',
          'kilicarslan' => 'Kılıçarslan',
          'korfez' => 'Körfez',
          'mahmutpasa' => 'Mahmutpaşa',
          'ovacik' => 'Ovacık',
          'pasadag' => 'Paşadağ',
          'sahil' => 'Sahil',
          'sepetlipinar' => 'Sepetlipınar',
          'serdar' => 'Serdar',
          'serindere' => 'Serindere',
          'servetiyecami' => 'Servetiyecami',
          'servetiyekarsi' => 'Servetiyekarşı',
          'seymen' => 'Seymen',
          'sehitekrem' => 'Şehitekrem',
          'tepecik' => 'Tepecik',
          'vezirciftligi' => 'Vezirçiftliği',
          'yuvacik-yakacik' => 'Yuvacık Yakacık',
          'yenikoy-merkez' => 'Yeniköy Merkez',
          'yesilkent' => 'Yeşilkent',
          'yesilyurt' => 'Yeşilyurt',
        ),
      ),
      'cayirova' => 
      array (
        'name' => 'Çayırova',
        'mahalleler' => 
        array (
          'akse' => 'Akse',
          'ataturk' => 'Atatürk',
          'cayirova' => 'Çayırova',
          'emek' => 'Emek',
          'inonu' => 'İnönü',
          'mutlukent' => 'Mutlukent',
          'ozgurluk' => 'Özgürlük',
          'sekerpinar' => 'Şekerpınar',
          'yeni' => 'Yeni',
        ),
      ),
      'darica' => 
      array (
        'name' => 'Darıca',
        'mahalleler' => 
        array (
          'abdi-ipekci' => 'Abdi İpekçi',
          'baglarbasi' => 'Bağlarbaşı',
          'bayramoglu' => 'Bayramoğlu',
          'cami' => 'Cami',
          'emek' => 'Emek',
          'fevzicakmak' => 'Fevziçakmak',
          'kazimkarabekir' => 'Kazımkarabekir',
          'nenehatun' => 'Nenehatun',
          'osmangazi' => 'Osmangazi',
          'piri-reis' => 'Piri Reis',
          'sirasogutler' => 'Sırasöğütler',
          'yali' => 'Yalı',
          'yeni' => 'Yeni',
          'zincirlikuyu' => 'Zincirlikuyu',
        ),
      ),
      'derince' => 
      array (
        'name' => 'Derince',
        'mahalleler' => 
        array (
          'cenedag' => 'Çenedağ',
          'cinarli' => 'Çınarlı',
          'deniz' => 'Deniz',
          'dumlupinar' => 'Dumlupınar',
          'fatih-sultan' => 'Fatih Sultan',
          'geredeli' => 'Geredeli',
          'ibni-sina' => 'İbni Sina',
          'karagollu' => 'Karagöllü',
          'kasikci' => 'Kaşıkçı',
          'mersincik' => 'Mersincik',
          'sirripasa' => 'Sırrıpaşa',
          'tahtali' => 'Tahtalı',
          'terzintarazi' => 'Terzibayırı',
          'toylar' => 'Toylar',
          'yavuz-sultan' => 'Yavuz Sultan',
          'yenikent' => 'Yenikent',
        ),
      ),
      'dilovasi' => 
      array (
        'name' => 'Dilovası',
        'mahalleler' => 
        array (
          'cerkesli' => 'Çerkeşli',
          'cumhuriyet' => 'Cumhuriyet',
          'demirciler' => 'Demirciler',
          'diliskelesi' => 'Diliskelesi',
          'fatih' => 'Fatih',
          'kayapinar' => 'Kayapınar',
          'koseler' => 'Köseler',
          'mimar-sinan' => 'Mimar Sinan',
          'orhangazi' => 'Orhangazi',
          'turgut-ozal' => 'Turgut Özal',
          'tavsancil' => 'Tavşancıl',
        ),
      ),
      'gebze' => 
      array (
        'name' => 'Gebze',
        'mahalleler' => 
        array (
          'adem-yavuz' => 'Adem Yavuz',
          'arapcesme' => 'Arapçeşme',
          'balcik' => 'Balçık',
          'baris' => 'Barış',
          'beylikbagi' => 'Beylikbağı',
          'cumakoy' => 'Cumaköy',
          'cumhuriyet' => 'Cumhuriyet',
          'denizli' => 'Denizli',
          'durakli' => 'Duraklı',
          'elbizli' => 'Elbizli',
          'eskihisar' => 'Eskihisar',
          'gaziler' => 'Gaziler',
          'guzeller' => 'Güzeller',
          'hacihalil' => 'Hacıhalil',
          'hatipler' => 'Hatipler',
          'hurriyet' => 'Hürriyet',
          'inonu' => 'İnönü',
          'istasyon' => 'İstasyon',
          'kadilli' => 'Kadıllı',
          'kargali' => 'Kargalı',
          'kirazpinar' => 'Kirazpınar',
          'kosklu-cesme' => 'Köşklü Çeşme',
          'mevlana' => 'Mevlana',
          'mimar-sinan' => 'Mimar Sinan',
          'mollafenari' => 'Mollafenari',
          'muallim' => 'Muallim',
          'mudarli' => 'Mudarlı',
          'mustafapasa' => 'Mustafapaşa',
          'osman-yilmaz' => 'Osman Yılmaz',
          'ovacik' => 'Ovacık',
          'pelitli' => 'Pelitli',
          'sultan-orhan' => 'Sultan Orhan',
          'tatlikuyu' => 'Tatlıkuyu',
          'tavsanli' => 'Tavşanlı',
          'tepemanayir' => 'Tepemanayır',
          'ulus' => 'Ulus',
          'yagcilar' => 'Yağcılar',
          'yavuz-selim' => 'Yavuz Selim',
          'yenikent' => 'Yenikent',
        ),
      ),
      'golcuk' => 
      array (
        'name' => 'Gölcük',
        'mahalleler' => 
        array (
          'ataturk' => 'Atatürk',
          'ayvazpinar' => 'Ayvazpınar',
          'degirmendere-merkez' => 'Değirmendere Merkez',
          'degirmendere-yali' => 'Değirmendere Yalı',
          'donanma' => 'Donanma',
          'dumlupinar' => 'Dumlupınar',
          'duzagac' => 'Düzağaç',
          'eskiferhadiye' => 'Eskiferhadiye',
          'ferhadiye' => 'Ferhadiye',
          'halidere-korfez' => 'Halıdere Körfez',
          'halidere-yali' => 'Halıdere Yalı',
          'hamidiye' => 'Hamidiye',
          'hasaneyn' => 'Hasaneyn',
          'hisareyn-merkez' => 'Hisareyn Merkez',
          'icadiye' => 'İcadiye',
          'ihsaniye-merkez' => 'İhsaniye Merkez',
          'ipekyolu' => 'İpekyolu',
          'irsadiye' => 'İrşadiye',
          'karakopru' => 'Karaköprü',
          'kavakli' => 'Kavaklı',
          'lutfiye' => 'Lütfiye',
          'mamuriye' => 'Mamuriye',
          'merkez' => 'Merkez',
          'nimetiye' => 'Nimetiye',
          'nuzhetiye' => 'Nüzhetiye',
          'orcun' => 'Örcün',
          'panayir' => 'Panayır',
          'piyalepasa' => 'Piyalepaşa',
          'sarayli' => 'Saraylı',
          'selimiye' => 'Selimiye',
          'siyretiye' => 'Siyretiye',
          'sofular' => 'Sofular',
          'sehitler' => 'Şehitler',
          'sevketye' => 'Şevketiye',
          'sirinkoy' => 'Şirinköy',
          'topcular' => 'Topçular',
          'ulasli-yali' => 'Ulaşlı Yalı',
          'ulasli-yavuz-sultan-selim' => 'Ulaşlı Yavuz Sultan Selim',
          'ummiye' => 'Ümmiye',
          'yazlik-merkez' => 'Yazlık Merkez',
          'yazlik-yeni' => 'Yazlık Yeni',
          'yeni' => 'Yeni',
        ),
      ),
      'kandira' => 
      array (
        'name' => 'Kandıra',
        'mahalleler' => 
        array (
          'akdurak' => 'Akdurak',
          'akinci' => 'Akıncı',
          'aydinlik' => 'Aydınlık',
          'carsi' => 'Çarşı',
          'orhan' => 'Orhan',
        ),
      ),
      'karamursel' => 
      array (
        'name' => 'Karamürsel',
        'mahalleler' => 
        array (
          '4-temmuz' => '4 Temmuz',
          'akcat' => 'Akçat',
          'avcikoy' => 'Avcıköy',
          'camcukur' => 'Çamçukur',
          'camiatik' => 'Camiatik',
          'derekoy' => 'Dereköy',
          'eregli' => 'Ereğli',
          'fulacik' => 'Fulacık',
          'hayriye' => 'Hayriye',
          'ihsaniye' => 'İhsaniye',
          'inebeyli' => 'İnebeyli',
          'ismailaga' => 'İsmailağa',
          'kadriye' => 'Kadriye',
          'karaahmetli' => 'Karaahmetli',
          'karapinar' => 'Karapınar',
          'kayacik' => 'Kayacık',
          'kizderbent' => 'Kızderbent',
          'nusretiye' => 'Nusretiye',
          'oluklu' => 'Oluklu',
          'osmaniye' => 'Osmaniye',
          'pazarkoy' => 'Pazarköy',
          'safiye' => 'Safiye',
          'semetler' => 'Semetler',
          'suludere' => 'Suludere',
          'tahtali' => 'Tahtalı',
          'tepekoy' => 'Tepeköy',
          'yalakdere' => 'Yalakdere',
        ),
      ),
      'kartepe' => 
      array (
        'name' => 'Kartepe',
        'mahalleler' => 
        array (
          'acisu' => 'Acısu',
          'arslanbey' => 'Arslanbey',
          'atasehir' => 'Ataşehir',
          'ataevler' => 'Ataevler',
          'balaban' => 'Balaban',
          'cepni' => 'Çepni',
          'derbent' => 'Derbent',
          'dumlupinar' => 'Dumlupınar',
          'emekevler' => 'Emekevler',
          'ertugrul-gazi' => 'Ertuğrul Gazi',
          'esme' => 'Eşme',
          'esmeahmediye' => 'Eşmeahmediye',
          'fatih-sultan-mehmet' => 'Fatih Sultan Mehmet',
          'hasanpasa' => 'Hasanpaşa',
          'havluburun' => 'Havluburun',
          'ibrikdere' => 'İbrikdere',
          'istasyon' => 'İstasyon',
          'karatepe' => 'Karatepe',
          'ketenciler' => 'Ketenciler',
          'kosekoy' => 'Köseköy',
          'nusretiye' => 'Nusretiye',
          'pazarcayiri' => 'Pazarçayırı',
          'rahmiye' => 'Rahmiye',
          'sarimese' => 'Sarımeşe',
          'serinlik' => 'Serinlik',
          'suadiye' => 'Suadiye',
          'sultaniye' => 'Sultaniye',
          'sefkatiye' => 'Şefkatiye',
          'sevkatiye' => 'Şevkatiye',
          'uzunbey' => 'Uzunbey',
          'uzunciftlik' => 'Uzunçiftlik',
          'uzuntarla' => 'Uzuntarla',
        ),
      ),
      'korfez' => 
      array (
        'name' => 'Körfez',
        'mahalleler' => 
        array (
          '17-agustos' => '17 Ağustos',
          'agah-ates' => 'Agah Ateş',
          'alihocalar' => 'Alihocalar',
          'atalar' => 'Atalar',
          'barbaros' => 'Barbaros',
          'belen' => 'Belen',
          'camlitepe' => 'Çamlıtepe',
          'cuma' => 'Cuma',
          'cumhuriyet' => 'Cumhuriyet',
          'derekoy' => 'Dereköy',
          'dikenli' => 'Dikenli',
          'elmacik' => 'Elmacık',
          'esentepe' => 'Esentepe',
          'fatih' => 'Fatih',
          'guney' => 'Güney',
          'haci-akif' => 'Hacı Akif',
          'haci-osman' => 'Hacı Osman',
          'himmetli' => 'Himmetli',
          'ilimtepe' => 'İlimtepe',
          'kalburcu' => 'Kalburcu',
          'kirazliyali' => 'Kirazlıyalı',
          'kisladuzu' => 'Kışladüzü',
          'kutluca' => 'Kutluca',
          'kuzey' => 'Kuzey',
          'mimar-sinan' => 'Mimar Sinan',
          'naip' => 'Naip',
          'sevindikli' => 'Sevindikli',
          'sipahiler' => 'Sipahiler',
          'semsettin' => 'Şemsettin',
          'sirinyali' => 'Şirinyalı',
          'yavuz-sultan-selim' => 'Yavuz Sultan Selim',
          'yeni-yali' => 'Yeni Yalı',
        ),
      ),
    ),
  ),
  'sakarya' => 
  array (
    'name' => 'Sakarya',
    'ilceler' => 
    array (
      'adapazari' => 
      array (
        'name' => 'Adapazarı',
        'mahalleler' => 
        array (
          'seker' => 'Şeker',
          'yagcilar' => 'Yağcılar',
          'cumhuriyet' => 'Cumhuriyet',
          'semerciler' => 'Semerciler',
          'orta' => 'Orta',
          'yeni' => 'Yeni',
          'yenigun' => 'Yenigün',
          'tepekum' => 'Tepekum',
          'tigcilar' => 'Tığcılar',
          'tuzla' => 'Tuzla',
          'istiklal' => 'İstiklal',
          'hizirtepe' => 'Hızırtepe',
          'maltepe' => 'Maltepe',
          'mithatpasa' => 'Mithatpaşa',
          'kurtulus' => 'Kurtuluş',
          'ozanlar' => 'Ozanlar',
          'papuccular' => 'Papuççular',
          'rustemler' => 'Rüstemler',
          'sakarya' => 'Sakarya',
          'suleymanbey' => 'Süleymanbey',
          'tekeler' => 'Tekeler',
          'yahyalar' => 'Yahyalar',
          'yenidogan' => 'Yenidoğan',
          'cukurahmediye' => 'Çukurahmediye',
          'karaman' => 'Karaman',
          'camili' => 'Camili',
          'korucuk' => 'Korucuk',
          'gulluk' => 'Güllük',
        ),
      ),
      'akyazi' => 
      array (
        'name' => 'Akyazı',
        'mahalleler' => 
        array (
          'fatih' => 'Fatih',
          'gazi-suleyman-pasa' => 'Gazi Süleyman Paşa',
          'hastane' => 'Hastane',
          'inonu' => 'İnönü',
          'konuralp' => 'Konuralp',
          'kuzuluk' => 'Kuzuluk',
          'omercikler' => 'Ömercikler',
          'yeni' => 'Yeni',
          'yunus-emre' => 'Yunus Emre',
        ),
      ),
      'arifiye' => 
      array (
        'name' => 'Arifiye',
        'mahalleler' => 
        array (
          'arifbey' => 'Arifbey',
          'fatih' => 'Fatih',
          'hanli' => 'Hanlı',
          'kumbasi' => 'Kumbaşı',
          'neviye' => 'Neviye',
          'yukarikirazca' => 'Yukarıkirazca',
        ),
      ),
      'erenler' => 
      array (
        'name' => 'Erenler',
        'mahalleler' => 
        array (
          'baglar' => 'Bağlar',
          'bekirpasa' => 'Bekirpaşa',
          'cubukcu' => 'Çubukçu',
          'dilmen' => 'Dilmen',
          'erenler' => 'Erenler',
          'hacioglu' => 'Hacıoğlu',
          'kupculer' => 'Küpçüler',
          'nakislar' => 'Nakışlar',
          'pirahmetler' => 'Pirahmetler',
          'tabakhane' => 'Tabakhane',
          'yeni' => 'Yeni',
          'yesiltepe' => 'Yeşiltepe',
        ),
      ),
      'ferizli' => 
      array (
        'name' => 'Ferizli',
        'mahalleler' => 
        array (
          'devlet' => 'Devlet',
          'golkent' => 'Gölkent',
          'inonu' => 'İnönü',
          'istiklal' => 'İstiklal',
          'kemalpasa' => 'Kemalpaşa',
        ),
      ),
      'geyve' => 
      array (
        'name' => 'Geyve',
        'mahalleler' => 
        array (
          'camikebir' => 'Camikebir',
          'gazi-suleyman-pasa' => 'Gazi Süleyman Paşa',
          'inciksuyu' => 'İnciksuyu',
          'orhaniye' => 'Orhaniye',
          'tepecikler' => 'Tepecikler',
        ),
      ),
      'hendek' => 
      array (
        'name' => 'Hendek',
        'mahalleler' => 
        array (
          'akova' => 'Akova',
          'baspinar' => 'Başpınar',
          'bayraktepe' => 'Bayraktepe',
          'buyukdere' => 'Büyükdere',
          'ciftlik' => 'Çiftlik',
          'kemaliye' => 'Kemaliye',
          'mahmutbey' => 'Mahmutbey',
          'rasimpasa' => 'Rasimpaşa',
          'turanlar' => 'Turanlar',
          'yeni' => 'Yeni',
        ),
      ),
      'karapurcek' => 
      array (
        'name' => 'Karapürçek',
        'mahalleler' => 
        array (
          'cumhuriyet' => 'Cumhuriyet',
          'inonu' => 'İnönü',
          'teketaban' => 'Teketaban',
        ),
      ),
      'karasu' => 
      array (
        'name' => 'Karasu',
        'mahalleler' => 
        array (
          'aziziye' => 'Aziziye',
          'incilli' => 'İncilli',
          'kabakoz' => 'Kabakoz',
          'kuzuluk' => 'Kuzuluk',
          'yali' => 'Yalı',
          'yeni' => 'Yeni',
        ),
      ),
      'kaynarca' => 
      array (
        'name' => 'Kaynarca',
        'mahalleler' => 
        array (
          'birlik' => 'Birlik',
          'hatipler' => 'Hatipler',
          'konak' => 'Konak',
          'merkez' => 'Merkez',
          'orta' => 'Orta',
        ),
      ),
      'kocaali' => 
      array (
        'name' => 'Kocaali',
        'mahalleler' => 
        array (
          'agalar' => 'Ağalar',
          'karsi' => 'Karşı',
          'merkez' => 'Merkez',
          'yali' => 'Yalı',
          'yeni' => 'Yeni',
        ),
      ),
      'pamukova' => 
      array (
        'name' => 'Pamukova',
        'mahalleler' => 
        array (
          'cumhuriyet' => 'Cumhuriyet',
          'elperek' => 'Elperek',
          'gonca' => 'Gonca',
          'incirli' => 'İncirli',
          'yenice' => 'Yenice',
        ),
      ),
      'sapanca' => 
      array (
        'name' => 'Sapanca',
        'mahalleler' => 
        array (
          'camii-cedit' => 'Camii Cedit',
          'gazipasa' => 'Gazipaşa',
          'guldibi' => 'Güldibi',
          'kirkpinar-hasanpasa' => 'Kırkpınar Hasanpaşa',
          'kirkpinar-soguksu' => 'Kırkpınar Soğuksu',
          'kurtkoy-fatih' => 'Kurtköy Fatih',
          'kurtkoy-yavuzselim' => 'Kurtköy Yavuzselim',
          'rustempasa' => 'Rüstempaşa',
          'uzunkum' => 'Uzunkum',
          'yanik' => 'Yanık',
        ),
      ),
      'serdivan' => 
      array (
        'name' => 'Serdivan',
        'mahalleler' => 
        array (
          'arabacialani' => 'Arabacıalanı',
          'bahcelievler' => 'Bahçelievler',
          'beskopru' => 'Beşköprü',
          'esentepe' => 'Esentepe',
          'istiklal' => 'İstiklal',
          'kemalpasa' => 'Kemalpaşa',
          'koprubasi' => 'Köprübaşı',
          'otuziki-evler' => 'Otuziki Evler',
          'serdivan' => 'Serdivan',
          'vatan' => 'Vatan',
          'yazlik' => 'Yazlık',
        ),
      ),
      'sogutlu' => 
      array (
        'name' => 'Söğütlü',
        'mahalleler' => 
        array (
          'akgol' => 'Akgöl',
          'camicedit' => 'Camicedit',
          'gundogan' => 'Gündoğan',
          'orta' => 'Orta',
        ),
      ),
      'tarakli' => 
      array (
        'name' => 'Taraklı',
        'mahalleler' => 
        array (
          'hacimurat' => 'Hacımurat',
          'haciyakup' => 'Hacıyakup',
          'ulucami' => 'Ulucami',
        ),
      ),
    ),
  ),
);
